name: Cypress Tests Run on Pipeline

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Npm Install
        run: npm install
      - name: Run Cypress
        run: npx cypress run
      - name: Upload screenshot artifacts
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - name: Upload video artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

